/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { V3Path, V3PathInterface } from "../V3Path";

const _abi = [
  {
    inputs: [],
    name: "SliceOutOfBounds",
    type: "error",
  },
];

const _bytecode =
  "0x6080806040523460175760119081601d823930815050f35b600080fdfe600080fdfea164736f6c6343000811000a";

export class V3Path__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<V3Path> {
    return super.deploy(overrides || {}) as Promise<V3Path>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): V3Path {
    return super.attach(address) as V3Path;
  }
  connect(signer: Signer): V3Path__factory {
    return super.connect(signer) as V3Path__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): V3PathInterface {
    return new utils.Interface(_abi) as V3PathInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): V3Path {
    return new Contract(address, _abi, signerOrProvider) as V3Path;
  }
}
